name: Deploy Vite React Portfolio to GitHub Pages

on:
  push:
    branches: ["main"]   # or "master" if that's your branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # Vite + React works great on Node 18

      - name: Install dependencies
        run: npm ci           # uses package-lock.json for clean install

      - name: Build project
        run: npm run build    # this will output to dist/

      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
